name: Run Go Script

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Go script
        run: go run main.go

      - name: Commit files
        run: bash .github/commit-script.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
